### ISSUE TITLE
Import failures from HSDS3.0 Airtable

### ISSUE THREAD

**Issue by royappa** [sarapis/orservices#134]
When importing from the sample HSDS3.0 Airtable provided, there are 2 "Service" entries but only one is crossing over.
The import succeeds but there is this in the storage/logs/laravel.log file. 

It might be that the dump 06032024.sql provided in the latest commit, compatible with an existing HSDS 3.0 Airtable file? The integrity violations are making me think it may not be. But without the data in the 06032024.sql dump file, I can't get the site up with an empty database just to login and add things via the admin backend.

```
[2024-03-07 03:04:33] local.ERROR: Error in Service: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'service_organizations.PRIMARY' (SQL: insert into `service_organizations` (`service_recordid`, `organization_recordid`, `updated_at`, `created_at`) values (1203987078426317, 1099602502219243, 2024-03-07 03:04:33, 2024-03-07 03:04:33))
[2024-03-07 03:04:37] local.ERROR: Error in Organization sync : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'service_organizations.PRIMARY' (SQL: insert into `service_organizations` (`organization_recordid`, `service_recordid`) values (1099602502219243, 1203987078426317))
[2024-03-07 03:04:40] local.ERROR: Error in Taxonomy: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'taxonomy_terms.PRIMARY' (SQL: insert into `taxonomy_terms` (`taxonomy_recordid`, `taxonomy_type_recordid`) values (587783173237318, 1306362890162801))
[2024-03-07 03:04:41] local.ERROR: Error in x-taxonomies: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'taxonomy_terms.PRIMARY' (SQL: insert into `taxonomy_terms` (`taxonomy_recordid`, `taxonomy_type_recordid`) values (730904153623137, 651915375766382))
[2024-03-07 03:04:44] local.ERROR: Error in applying geocode in import : TypeError: Spatie\Geocoder\Geocoder::setApiKey(): Argument #1 ($apiKey) must be of type string, null given, called in /var/www/ors/app/Http/Controllers/backend/ImportController.php on line 1097 and defined in /var/www/ors/vendor/spatie/geocoder/src/Geocoder.php:38


Stack trace:
#0 /var/www/ors/app/Http/Controllers/backend/ImportController.php(1097): Spatie\Geocoder\Geocoder->setApiKey()
#1 /var/www/ors/app/Http/Controllers/backend/ImportController.php(645): App\Http\Controllers\backend\ImportController->apply_geocode()
#2 /var/www/ors/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\backend\ImportController->importData()
#3 /var/www/ors/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#4 /var/www/ors/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch()
#5 /var/www/ors/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#6 /var/www/ors/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Route->run()
#7 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#8 /var/www/ors/app/Http/Middleware/Permissions.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#9 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\Http\Middleware\Permissions->handle()
#10 /var/www/ors/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#12 /var/www/ors/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Auth\Middleware\Authenticate->handle()
#14 /var/www/ors/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#15 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#16 /var/www/ors/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#18 /var/www/ors/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /var/www/ors/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#20 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#21 /var/www/ors/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#23 /var/www/ors/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#25 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /var/www/ors/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\Pipeline\Pipeline->then()
#27 /var/www/ors/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\Routing\Router->runRouteWithinStack()
#28 /var/www/ors/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\Routing\Router->runRoute()
#29 /var/www/ors/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\Routing\Router->dispatchToRoute()
#30 /var/www/ors/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\Routing\Router->dispatch()
#31 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#32 /var/www/ors/app/Http/Middleware/TimeZoneMiddleware.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\Http\Middleware\TimeZoneMiddleware->handle()
#34 /var/www/ors/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /var/www/ors/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#36 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#37 /var/www/ors/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 /var/www/ors/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#39 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#40 /var/www/ors/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#42 /var/www/ors/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#44 /var/www/ors/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#46 /var/www/ors/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /var/www/ors/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then()
#48 /var/www/ors/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#49 /var/www/ors/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle()
#50 {main}
```

**Comment by d9it** [comment]
Fixed now, you can import using a latest dump file.
